Repository neherlab/covid19_scenarios, pull requests merged in 2020-04, with the labels that each got.

#319 Fix-tests / Update snapshots for tests broken by changes in #313.
  src/algorithms/__snapshots__/model.test.ts.snap
Labels: IMPORTANT, pr: under review

#263 Layout improvement faq team
  src/assets/text/faq.md
  src/assets/text/updates.md
  src/components/Layout/Layout.scss
  src/components/Layout/Layout.tsx
  src/components/Layout/NavigationBar.scss
  src/components/Layout/NavigationBar.tsx
  src/links.ts
  src/locales/en/translation.json
  src/locales/pt/translation.json
  src/pages/About.mdx
  src/pages/About.scss
  src/pages/Acknowledgements.mdx
  src/pages/Acknowledgements.scss
  src/pages/DefaultStatic.scss
  src/pages/Faq.mdx
  src/pages/FaqTableOfContents.tsx
  src/pages/Team.tsx
  src/pages/Updates.mdx
  src/routes.ts
Labels: pr: work in progress

#323 feat: add interval-based mitigation widget [WIP]
  package.json
  src/algorithms/run.ts
  src/algorithms/types/Param.types.ts
  src/algorithms/utils/TimeSeries.test.ts
  src/algorithms/utils/TimeSeries.ts
  src/algorithms/utils/__snapshots__/TimeSeries.test.ts.snap
  src/algorithms/utils/createMitigationInterval.ts
  src/algorithms/utils/userResult.ts
  src/assets/data/scenarios/scenarios.json
  src/assets/data/scenarios/scenarios.ts
  src/components/Form/DateRangePicker.tsx
  src/components/Form/FormDatePicker.tsx
  src/components/Form/HelpLabel.tsx
  src/components/Main/Containment/ContainmentGraph.tsx
  src/components/Main/Main.tsx
  src/components/Main/Mitigation/MitigationDatePicker.tsx
  src/components/Main/Mitigation/MitigationTable.scss
  src/components/Main/Mitigation/MitigationTable.tsx
  src/components/Main/Results/DeterministicLinePlot.tsx
  src/components/Main/Results/ResultsCard.tsx
  src/components/Main/Scenario/ScenarioCardContainment.tsx
  src/components/Main/state/data.ts
  src/components/Main/state/reducer.ts
  src/components/Main/state/state.ts
  src/types/create-color.d.ts
  yarn.lock
Labels: IMPORTANT, pr: work in progress, s:algo, s:ui, t:feat

#378 Drag/Resize Scenario and Results vs. Zoom in/out chart
  package.json
  src/components/Main/Main.tsx
  src/components/Main/Results/DeterministicLinePlot.tsx
  src/styles/global.scss
  yarn.lock
Labels: t:feat

#434 feat: AgeDistribution Schema array
  data/scripts/download_age_dists.py
  data/scripts/transform_ages.py
  package.json
  schemas/CountryAgeDistribution.yml
  src/algorithms/types/Param.types.ts
  src/assets/data/CountryAgeDistribution.types.ts
  src/assets/data/country_age_distribution.json
  src/components/Main/Scenario/ScenarioCardPopulation.tsx
  src/components/Main/state/caseCountsData.ts
  src/components/Main/state/countryAgeDistributionData.ts
  src/components/Main/state/reducer.ts
  src/components/Main/state/scenarioData.ts
  src/components/Main/state/state.ts
  src/components/Main/validation/schema.ts
  tools/convertSchemasToType.ts
  yarn.lock
Labels: IMPORTANT, pr: work in progress, t:feat

#471 Feat/print pdf
  src/algorithms/types/Param.types.ts
  src/components/Layout/Layout.tsx
  src/components/Main/Main.tsx
  src/components/Main/PrintPage/PrintPage.scss
  src/components/Main/PrintPage/PrintPage.tsx
  src/components/Main/PrintPage/TableResult.tsx
  src/components/Main/Results/AgeBarChart.tsx
  src/components/Main/Results/DeterministicLinePlot.tsx
  src/components/Main/Results/ExportSimulationDialog.tsx
  src/components/Main/Results/OutcomeRatesTable.tsx
  src/components/Main/Results/ResultsCard.tsx
  src/pages/Home.tsx
Labels: IMPORTANT, help wanted, pr: work in progress, s:ui

#554 Feat: Pull in population and hospital data from CIA facts
  data/populationData.tsv
  data/scripts/getPopulationData.py
Labels: s:data

#553 ITA-TrentionAltoAdige aggregation
  data/case-counts/italy/ITA-TrentionAltoAdige.tsv
  data/parsers/italy.py
  data/parsers/utils.py
  data/populationData.tsv
Labels: s:data

#537 Model uncertainty in input parameters
  data/scripts/scenarios.py
  package.json
  schemas/Scenarios.yml
  src/algorithms/__snapshots__/model.test.ts.snap
  src/algorithms/initialize.ts
  src/algorithms/mitigation.ts
  src/algorithms/model.test.ts
  src/algorithms/model.ts
  src/algorithms/results.ts
  src/algorithms/run.ts
  src/algorithms/types/Result.types.ts
  src/algorithms/types/TimeSeries.types.ts
  src/algorithms/utils/createMitigationInterval.ts
  src/algorithms/utils/exportResult.ts
  src/algorithms/utils/sample.ts
  src/assets/data/scenarios/scenarios.json
  src/components/Form/FormRangeSlider.tsx
  src/components/Main/Main.tsx
  src/components/Main/Mitigation/MitigationTable.tsx
  src/components/Main/PrintPage/PrintPage.tsx
  src/components/Main/PrintPage/TableResult.tsx
  src/components/Main/Results/AgeBarChart.tsx
  src/components/Main/Results/ChartCommon.ts
  src/components/Main/Results/DeterministicLinePlot.tsx
  src/components/Main/Results/ExportSimulationDialog.tsx
  src/components/Main/Results/LinePlotTooltip.tsx
  src/components/Main/Results/MitigationLinePlot.tsx
  src/components/Main/Results/OutcomeRatesTable.tsx
  src/components/Main/Results/R0LinePlot.tsx
  src/components/Main/Results/ResponsiveTooltipContent.tsx
  src/components/Main/Results/ResultsCard.tsx
  src/components/Main/Scenario/ScenarioCardEpidemiological.tsx
  src/components/Main/validation/schema.ts
  yarn.lock
Labels: IMPORTANT, pr: work in progress, t:feat

#642 [Fix] Update the age stratified chart to have error bars
  src/components/Main/PrintPage/PrintPage.tsx
  src/components/Main/PrintPage/TableResult.tsx
  src/components/Main/Results/AgeBarChart.tsx
  src/components/Main/Results/ChartTooltip.tsx
  src/components/Main/Results/OutcomeRatesTable.tsx
  src/components/Main/Scenario/ScenarioCardContainment.tsx
Labels: IMPORTANT, s:ui
