Repository neherlab/covid19_scenarios, pull requests merged in 2020-03, with the labels that each got.

#96 [housekeeping] Fix LineProps['legendType'] type-safety with <Line />
  src/components/Main/Results/DeterministicLinePlot.tsx
Labels: pr: work in progress

#99 Fix crash when inputing number below 2 on ContainmentGraph
  src/components/Form/FormSpinBox.tsx
  src/components/Main/Containment/ContainmentGraph.tsx
  src/components/Main/Scenario/ScenarioCardContainment.tsx
Labels: pr: under review

#85 Issue #56: Extract strings for translation
  src/assets/data/scenarios/containment.ts
  src/assets/data/scenarios/overall.ts
  src/components/Main/Compare/ComparisonModalWithButton.tsx
  src/components/Main/Compare/FileUploadZone.tsx
  src/components/Main/Results/AgeBarChart.tsx
  src/components/Main/Results/DeterministicLinePlot.tsx
  src/components/Main/Results/OutcomeRatesTable.tsx
  src/components/Main/Results/ResultsCard.tsx
  src/components/Main/Scenario/ScenarioCard.tsx
  src/components/Main/Scenario/ScenarioCardContainment.tsx
  src/components/Main/Scenario/ScenarioCardEpidemiological.tsx
  src/components/Main/Scenario/ScenarioCardPopulation.tsx
  src/components/Main/Scenario/SeverityCard.tsx
  src/components/Main/Scenario/SeverityTable.tsx
  src/components/Main/Scenario/validatePercentage.ts
  src/components/Main/state/state.ts
  src/components/Main/validation/schema.ts
  src/i18n.ts
  src/links.ts
  src/locales/en/translation.json
  src/locales/fr/translation.json
  src/pages/ErrorPage.tsx
  src/pages/Loading.tsx
  src/pages/NotFound.tsx
  src/pages/Team.tsx
Labels: pr: needs rebase

#103 Scroll ResultsCard into view when "Run" is tapped
  src/components/Main/Main.tsx
  src/components/Main/Results/ResultsCard.tsx
  src/helpers/hooks.ts
Labels: pr: under review

#100 #19/add timeseries tests
  src/algorithms/test/TimeSeries.test.ts
Labels: pr: under review

#161 Model JS -> TS Conversion
  src/algorithms/model.js
  src/algorithms/model.ts
  src/algorithms/test/model.test.ts
  src/algorithms/types/Result.types.ts
  src/assets/data/test/containment.default.json
  src/assets/data/test/evolve.output.5th.default.json
  src/assets/data/test/getPopulationParams.input.default.json
  src/assets/data/test/getPopulationParams.output.default.json
  src/assets/data/test/initializePopulation.input.default.json
  src/assets/data/test/initializePopulation.output.default.json
Labels: pr: under review

#152 amend german translation
  src/locales/de/translation.json
Labels: pr: work in progress

#194 Change linear interpolation to spline
  package.json
  src/algorithms/run.ts
  src/algorithms/test/TimeSeries.test.ts
  src/algorithms/test/__snapshots__/TimeSeries.test.ts.snap
  src/algorithms/test/__snapshots__/model.test.ts.snap
  src/algorithms/test/model.test.ts
  src/algorithms/utils/TimeSeries.ts
  src/assets/data/test/evolve.output.5th.default.json
  src/components/Main/state/reducer.ts
  yarn.lock
Labels: IMPORTANT, help wanted, pr: work in progress

#252 add cumulative fields to export, fix time
  src/algorithms/model.ts
  src/algorithms/utils/exportResult.ts
  src/components/Main/Results/ExportSimulationDialog.tsx
Labels: IMPORTANT, pr: needs help, pr: needs rebase, pr: under review

#237 Feat: Responsive tooltips
  src/components/Main/Results/AgeBarChart.tsx
  src/components/Main/Results/DeterministicLinePlot.tsx
  src/components/Main/Results/ResponsiveTooltipContent.scss
  src/components/Main/Results/ResponsiveTooltipContent.tsx
  src/components/Main/Results/chartHelper.ts
  src/styles/global.scss
Labels: pr: needs rebase, pr: under review

#272 Refactor local storage
  .gitignore
  src/components/LandingPage/LandingPage.tsx
  src/helpers/localStorage.ts
  src/state/ui/ui.reducer.ts
Labels: pr: under review

#280 [WIP] Improving SEO meta tags
  .env.example
  config/webpack/webpack.client.babel.ts
  now.json
  src/index.ejs
Labels: pr: needs rebase, s:ui

#313 Lowered euler step size
  src/algorithms/model.ts
  src/algorithms/run.ts
  src/components/Main/Results/DeterministicLinePlot.tsx
Labels: IMPORTANT, pr: under review, s:algo
